### ISSUE TITLE
Images for repo

### ISSUE THREAD

**Issue by PelayoChoya** [PelayoChoya/ACO_path_planning#1]
This issue contains the images used for the repo

**Comment by PelayoChoya** [comment]
![map3_2](https://user-images.githubusercontent.com/23075158/33822996-d2bd8668-de59-11e7-849a-313333f6d8bf.png)

**Comment by PanosMallioris** [comment]
Hello Pelayo,

I am trying to execute the simulation but i get this error when i execute $ aco_resolve_path.py :

   aco_resolve_path.py: error: too few arguments

Also since executed i have some pyc files on my aco repository which i cant open

Any advice?

**Comment by PelayoChoya** [comment]
Hello,

The script needs some arguments to be introduced, you can see which these are by executing:

`python aco_resolve_path.py --help`

The pyc files are compiled python code, you shouldn't be looking at them.

Regards,

**Comment by PanosMallioris** [comment]
Hello Pelayo,

Can you please explain me how to introduce these arguments?(ants,iterations,p,q) 
I tried to use set -- in the terminal but there is no such option.

Thanks,
